name: Deploy to Firebase Hosting

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - claude/scheduling-attendance-app-zxwsP

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Hello test
        run: echo "Runner works!"
